"""Add the  Hash password column and remove the Password Column in DB

Revision ID: eb53277e8b82
Revises: fe44dcea49b8
Create Date: 2026-05-01 23:28:56.856492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb53277e8b82'
down_revision: Union[str, Sequence[str], None] = 'fe44dcea49b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
