"""Add the Hash password column

Revision ID: fe44dcea49b8
Revises: 3186532a680d
Create Date: 2026-05-01 23:14:04.379810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe44dcea49b8'
down_revision: Union[str, Sequence[str], None] = '3186532a680d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash_pw', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hash_pw')
    # ### end Alembic commands ###
